import React from "react";
import logo from "./logo.svg";
import "./App.css";
import TextField from "./components/TextField";
import Button from "./components/Button";
import PPopover from "./components/Popover";

function App() {
  return (
    <>
      <div className="App">
        <h1>TextField component</h1>
        <div className="w-96">
          <TextField
            label="TextField test label"
            helperText="TextField helper test"
          />
          <TextField
            label="TextField success label"
            helperText="TextField helper success"
            status="success"
          />
          <TextField
            label="TextField error label"
            helperText="TextField helper error"
            status="error"
          />
          <TextField
            label="TextField warning label"
            helperText="TextField helper warning "
            status="warning"
          />
        </div>

        <h1>Button component</h1>
        <div className="w-128">
          <div>
            <Button
              status="default"
              disabled={false}
              isLoading={false}
              intent="primary"
            >
              Button
            </Button>
            <Button
              status="default"
              disabled={true}
              isLoading={false}
              intent="primary"
            >
              Button
            </Button>
            <Button
              status="default"
              disabled={false}
              isLoading={true}
              intent="primary"
            >
              Button
            </Button>
            <Button
              status="default"
              disabled={false}
              isLoading={false}
              intent="secondary"
            >
              Button
            </Button>
            <Button
              status="default"
              disabled={true}
              isLoading={false}
              intent="secondary"
            >
              Button
            </Button>
            <Button
              status="default"
              disabled={false}
              isLoading={true}
              intent="secondary"
            >
              Button
            </Button>
            <Button
              status="default"
              disabled={false}
              isLoading={false}
              intent="link"
            >
              Button
            </Button>
            <Button
              status="default"
              disabled={true}
              isLoading={false}
              intent="link"
            >
              Button
            </Button>
            <Button
              status="default"
              disabled={false}
              isLoading={true}
              intent="link"
            >
              Button
            </Button>
          </div>
          <div>
            <Button
              status="success"
              disabled={false}
              isLoading={false}
              intent="primary"
            >
              Button
            </Button>
            <Button
              status="success"
              disabled={true}
              isLoading={false}
              intent="primary"
            >
              Button
            </Button>
            <Button
              status="success"
              disabled={false}
              isLoading={true}
              intent="primary"
            >
              Button
            </Button>
            <Button
              status="success"
              disabled={false}
              isLoading={false}
              intent="secondary"
            >
              Button
            </Button>
            <Button
              status="success"
              disabled={true}
              isLoading={false}
              intent="secondary"
            >
              Button
            </Button>
            <Button
              status="success"
              disabled={false}
              isLoading={true}
              intent="secondary"
            >
              Button
            </Button>
            <Button
              status="success"
              disabled={false}
              isLoading={false}
              intent="link"
            >
              Button
            </Button>
            <Button
              status="success"
              disabled={true}
              isLoading={false}
              intent="link"
            >
              Button
            </Button>
            <Button
              status="success"
              disabled={false}
              isLoading={true}
              intent="link"
            >
              Button
            </Button>
          </div>
          <div>
            <Button
              status="error"
              disabled={false}
              isLoading={false}
              intent="primary"
            >
              Button
            </Button>
            <Button
              status="error"
              disabled={true}
              isLoading={false}
              intent="primary"
            >
              Button
            </Button>
            <Button
              status="error"
              disabled={false}
              isLoading={true}
              intent="primary"
            >
              Button
            </Button>
            <Button
              status="error"
              disabled={false}
              isLoading={false}
              intent="secondary"
            >
              Button
            </Button>
            <Button
              status="error"
              disabled={true}
              isLoading={false}
              intent="secondary"
            >
              Button
            </Button>
            <Button
              status="error"
              disabled={false}
              isLoading={true}
              intent="secondary"
            >
              Button
            </Button>
            <Button
              status="error"
              disabled={false}
              isLoading={false}
              intent="link"
            >
              Button
            </Button>
            <Button
              status="error"
              disabled={true}
              isLoading={false}
              intent="link"
            >
              Button
            </Button>
            <Button
              status="error"
              disabled={false}
              isLoading={true}
              intent="link"
            >
              Button
            </Button>
          </div>

          <div>
            <Button
              status="warning"
              disabled={false}
              isLoading={false}
              intent="primary"
            >
              Button
            </Button>
            <Button
              status="warning"
              disabled={true}
              isLoading={false}
              intent="primary"
            >
              Button
            </Button>
            <Button
              status="warning"
              disabled={false}
              isLoading={true}
              intent="primary"
            >
              Button
            </Button>
            <Button
              status="warning"
              disabled={false}
              isLoading={false}
              intent="secondary"
            >
              Button
            </Button>
            <Button
              status="warning"
              disabled={true}
              isLoading={false}
              intent="secondary"
            >
              Button
            </Button>
            <Button
              status="warning"
              disabled={false}
              isLoading={true}
              intent="secondary"
            >
              Button
            </Button>
            <Button
              status="warning"
              disabled={false}
              isLoading={false}
              intent="link"
            >
              Button
            </Button>
            <Button
              status="warning"
              disabled={true}
              isLoading={false}
              intent="link"
            >
              Button
            </Button>
            <Button
              status="warning"
              disabled={false}
              isLoading={true}
              intent="link"
            >
              Button
            </Button>
          </div>
        </div>
        <PPopover title="Popover">
          <div className="grid grid-cols-2">
            <a href="/a">Analytics</a>
            <a href="/">Engagement</a>
            <a href="/">Security</a>
            <a href="/">Integrations</a>
          </div>
        </PPopover>
      </div>
    </>
  );
}

export default App;
